

###
GET http://localhost/api/user/register
###

###
POST http://localhost/api/user/register
Content-Type: application/json
###


###
GET http://localhost/api/article
###

###
GET http://localhost/api/article/deletesinglepost/60825_2
###



###
GET http://localhost/api/article/singlepost2/8628579747890
###


###
POST http://localhost/api/article
Content-Type: application/json

{
    "ownerName":"ccc",
    "content":"cccdd"

}
###

###
GET http://localhost/api/picture
###

###
POST http://localhost/api/comment
Content-Type: application/json

{
    "ownerName":"ccc",
    "content":"cccdd",
    "postID":"Fdfewfsa",
    "postingTime":434534

}
###