


###
GET http://localhost/api/article
###


###
GET http://localhost/api/article/singlepost/3
###


###
POST http://localhost/api/article
Content-Type: application/json

{
    "ownerName":"ccc",
    "content":"cccdd"

}
###

###
GET http://localhost/api/picture
###